In [84]:
import pandas as pd

numpy, matplotlib, seaborn, sckit learn, scipy, keras(tensorflow), statmodels(regression analysis) :data science project

pandas is a library in python (panda(data analysis)) series and dataframe

Series (single dimensional array of data(list,string))
fruits = (apple, banana, mangoes)

Dataframe this is basically a multidemsional array of data (mixed string, list, float, boolean)
Usually in form of colums and rows like in a excel ,csv,sql

In [85]:
data = {
    'city': ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
    'population': [8419600, 3980400, 2716000, 2328000, 1690000],
    'area': [783.8, 503, 227.3, 637.4, 517.6]
}

In [86]:
df_cities = pd.DataFrame(data)
df_cities

          city  population   area
0     New York     8419600  783.8
1  Los Angeles     3980400  503.0
2      Chicago     2716000  227.3
3      Houston     2328000  637.4
4      Phoenix     1690000  517.6

In [87]:
data = pd.read_csv('DailyDelhiClimateTest.csv')
data

           date   meantemp   humidity  wind_speed  meanpressure
0    2017-01-01  15.913043  85.869565    2.743478     59.000000
1    2017-01-02  18.500000  77.222222    2.894444   1018.277778
2    2017-01-03  17.111111  81.888889    4.016667   1018.333333
3    2017-01-04  18.700000  70.050000    4.545000   1015.700000
4    2017-01-05  18.388889  74.944444    3.300000   1014.333333
..          ...        ...        ...         ...           ...
109  2017-04-20  34.500000  27.500000    5.562500    998.625000
110  2017-04-21  34.250000  39.375000    6.962500    999.875000
111  2017-04-22  32.900000  40.900000    8.890000   1001.600000
112  2017-04-23  32.875000  27.500000    9.962500   1002.125000
113  2017-04-24  32.000000  27.142857   12.157143   1004.142857

[114 rows x 5 columns]

In [88]:
#Manipulating data
type(data)

pandas.core.frame.DataFrame

In [89]:
#first 5 rows
data.head()

         date   meantemp   humidity  wind_speed  meanpressure
0  2017-01-01  15.913043  85.869565    2.743478     59.000000
1  2017-01-02  18.500000  77.222222    2.894444   1018.277778
2  2017-01-03  17.111111  81.888889    4.016667   1018.333333
3  2017-01-04  18.700000  70.050000    4.545000   1015.700000
4  2017-01-05  18.388889  74.944444    3.300000   1014.333333

In [90]:
#first 10 rows
data.head(10)

         date   meantemp   humidity  wind_speed  meanpressure
0  2017-01-01  15.913043  85.869565    2.743478     59.000000
1  2017-01-02  18.500000  77.222222    2.894444   1018.277778
2  2017-01-03  17.111111  81.888889    4.016667   1018.333333
3  2017-01-04  18.700000  70.050000    4.545000   1015.700000
4  2017-01-05  18.388889  74.944444    3.300000   1014.333333
5  2017-01-06  19.318182  79.318182    8.681818   1011.772727
6  2017-01-07  14.708333  95.833333   10.041667   1011.375000
7  2017-01-08  15.684211  83.526316    1.950000   1015.550000
8  2017-01-09  14.571429  80.809524    6.542857   1015.952381
9  2017-01-10  12.111111  71.944444    9.361111   1016.888889

In [91]:
#first 2 rows
data.head(2)

         date   meantemp   humidity  wind_speed  meanpressure
0  2017-01-01  15.913043  85.869565    2.743478     59.000000
1  2017-01-02  18.500000  77.222222    2.894444   1018.277778

In [92]:
#last 10 rows
data.tail()

           date  meantemp   humidity  wind_speed  meanpressure
109  2017-04-20    34.500  27.500000    5.562500    998.625000
110  2017-04-21    34.250  39.375000    6.962500    999.875000
111  2017-04-22    32.900  40.900000    8.890000   1001.600000
112  2017-04-23    32.875  27.500000    9.962500   1002.125000
113  2017-04-24    32.000  27.142857   12.157143   1004.142857

In [93]:
#to gather info from the data set
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          114 non-null    object
 1   meantemp      114 non-null    float64
 2   humidity      114 non-null    float64
 3   wind_speed    114 non-null    float64
 4   meanpressure  114 non-null    float64
dtypes: float64(4), object(1)
memory usage: 4.6+ KB

In [94]:
#shape of dataset
data.shape

(114, 5)

In [95]:
#iloc and loc
#iloc - interger location indexing(1,2,3)
#loc - label based indexing (labels are column names)

In [96]:
#to get second row
data.iloc[1]

date            2017-01-02
meantemp              18.5
humidity           77.2222
wind_speed         2.89444
meanpressure       1018.28
Name: 1, dtype: object

In [97]:
data.iloc[0]

date            2017-01-01
meantemp            15.913
humidity           85.8696
wind_speed         2.74348
meanpressure            59
Name: 0, dtype: object

In [98]:
# 1 row to 4 row
data.iloc[0:4]

         date   meantemp   humidity  wind_speed  meanpressure
0  2017-01-01  15.913043  85.869565    2.743478     59.000000
1  2017-01-02  18.500000  77.222222    2.894444   1018.277778
2  2017-01-03  17.111111  81.888889    4.016667   1018.333333
3  2017-01-04  18.700000  70.050000    4.545000   1015.700000

In [99]:
# first two columns
data.iloc[:, 0:2]

           date   meantemp
0    2017-01-01  15.913043
1    2017-01-02  18.500000
2    2017-01-03  17.111111
3    2017-01-04  18.700000
4    2017-01-05  18.388889
..          ...        ...
109  2017-04-20  34.500000
110  2017-04-21  34.250000
111  2017-04-22  32.900000
112  2017-04-23  32.875000
113  2017-04-24  32.000000

[114 rows x 2 columns]

In [100]:
#row 4-10 and column 2-4
data.iloc[4:11,2:5]

     humidity  wind_speed  meanpressure
4   74.944444    3.300000   1014.333333
5   79.318182    8.681818   1011.772727
6   95.833333   10.041667   1011.375000
7   83.526316    1.950000   1015.550000
8   80.809524    6.542857   1015.952381
9   71.944444    9.361111   1016.888889
10  72.111111    9.772222   1016.777778

In [101]:
#all columns
data.iloc[1:6, :]

         date   meantemp   humidity  wind_speed  meanpressure
1  2017-01-02  18.500000  77.222222    2.894444   1018.277778
2  2017-01-03  17.111111  81.888889    4.016667   1018.333333
3  2017-01-04  18.700000  70.050000    4.545000   1015.700000
4  2017-01-05  18.388889  74.944444    3.300000   1014.333333
5  2017-01-06  19.318182  79.318182    8.681818   1011.772727

In [102]:
# loc (label based indexing)
data.loc[:, 'meantemp']

0      15.913043
1      18.500000
2      17.111111
3      18.700000
4      18.388889
         ...
109    34.500000
110    34.250000
111    32.900000
112    32.875000
113    32.000000
Name: meantemp, Length: 114, dtype: float64

In [103]:
# used for specific column information
data.loc[data['meantemp']<20]

          date   meantemp   humidity  wind_speed  meanpressure
0   2017-01-01  15.913043  85.869565    2.743478     59.000000
1   2017-01-02  18.500000  77.222222    2.894444   1018.277778
2   2017-01-03  17.111111  81.888889    4.016667   1018.333333
3   2017-01-04  18.700000  70.050000    4.545000   1015.700000
4   2017-01-05  18.388889  74.944444    3.300000   1014.333333
5   2017-01-06  19.318182  79.318182    8.681818   1011.772727
6   2017-01-07  14.708333  95.833333   10.041667   1011.375000
7   2017-01-08  15.684211  83.526316    1.950000   1015.550000
8   2017-01-09  14.571429  80.809524    6.542857   1015.952381
9   2017-01-10  12.111111  71.944444    9.361111   1016.888889
10  2017-01-11  11.000000  72.111111    9.772222   1016.777778
11  2017-01-12  11.789474  74.578947    6.626316   1016.368421
12  2017-01-13  13.235294  67.058824    6.435294   1017.529412
13  2017-01-14  13.200000  74.280000    5.276000   1018.840000
14  2017-01-15  16.434783  72.565217    3.630435   1018.130435
15  2017-01-16  14.650000  78.450000   10.380000   1017.150000
16  2017-01-17  11.722222  84.444444    8.038889   1018.388889
17  2017-01-18  13.041667  78.333333    6.029167   1021.958333
18  2017-01-19  14.619048  75.142857   10.338095   1022.809524
19  2017-01-20  15.263158  66.473684   11.226316   1021.789474
20  2017-01-21  15.391304  70.869565   13.695652   1020.478261
21  2017-01-22  18.440000  76.240000    5.868000   1021.040000
22  2017-01-23  18.117647  76.000000    6.752941   1019.823529
23  2017-01-24  18.347826  68.130435    3.391304   1018.869565
25  2017-01-26  16.178571  91.642857    8.467857   1017.785714
26  2017-01-27  16.500000  77.041667   14.358333   1018.125000
27  2017-01-28  14.863636  82.772727    9.690909   1019.636364
28  2017-01-29  15.666667  81.777778   10.294444   1017.388889
29  2017-01-30  16.444444  77.555556    4.322222   1015.833333
30  2017-01-31  16.125000  76.000000    4.625000   1015.500000
31  2017-02-01  15.250000  78.625000    5.100000   1017.500000
32  2017-02-02  17.090909  66.545455    3.027273   1018.909091
33  2017-02-03  15.636364  78.181818    1.854545   1017.727273
34  2017-02-04  18.700000  77.600000    9.820000   1014.400000
35  2017-02-05  18.631579  77.631579    8.100000   1014.210526
36  2017-02-06  16.888889  69.666667    9.044444   1016.000000
37  2017-02-07  15.125000  63.750000    7.637500   1016.125000
38  2017-02-08  15.700000  68.400000    4.080000   1015.600000
39  2017-02-09  15.375000  68.375000    7.875000   1016.375000
40  2017-02-10  14.666667  71.777778    9.066667   1015.666667
41  2017-02-11  15.625000  64.000000    3.950000   1016.625000
42  2017-02-12  16.250000  70.375000    1.625000   1019.625000
43  2017-02-13  16.333333  67.000000    6.377778   1021.555556
44  2017-02-14  16.875000  65.500000    6.962500   1021.375000
45  2017-02-15  17.571429  67.714286    5.557143   1020.571429
52  2017-02-22  19.125000  57.125000    7.412500   1012.250000
53  2017-02-23  18.625000  42.875000   14.350000   1015.250000
54  2017-02-24  19.125000  40.375000   16.662500   1016.125000
55  2017-02-25  19.000000  50.428571   11.928571   1014.285714
56  2017-02-26  18.750000  59.000000   11.112500   1012.375000
57  2017-02-27  19.875000  58.375000    5.100000   1014.250000
62  2017-03-04  19.125000  43.125000    8.350000   1010.000000
63  2017-03-05  19.750000  41.250000    9.962500   1010.500000
68  2017-03-10  19.937500  67.750000   11.462500   1006.875000
69  2017-03-11  18.533333  60.400000    5.566667   1009.800000
70  2017-03-12  17.375000  56.625000    7.637500   1014.750000
71  2017-03-13  17.444444  49.333333    9.055556   1014.888889
72  2017-03-14  18.000000  56.333333    4.522222   1016.555556
73  2017-03-15  19.875000  54.750000    7.175000   1014.125000

In [104]:
# if temperature is less than 20 , equate it to 19
data.loc[data['meantemp'] < 20, 'meantemp']= 19
data.head()

         date  meantemp   humidity  wind_speed  meanpressure
0  2017-01-01      19.0  85.869565    2.743478     59.000000
1  2017-01-02      19.0  77.222222    2.894444   1018.277778
2  2017-01-03      19.0  81.888889    4.016667   1018.333333
3  2017-01-04      19.0  70.050000    4.545000   1015.700000
4  2017-01-05      19.0  74.944444    3.300000   1014.333333

In [105]:
data.loc[data['humidity']<50, 'temperature'] = 'cold'
data.loc[data['humidity']>50, 'temperature'] = 'hot'
data

           date  meantemp   humidity  wind_speed  meanpressure temperature
0    2017-01-01    19.000  85.869565    2.743478     59.000000         hot
1    2017-01-02    19.000  77.222222    2.894444   1018.277778         hot
2    2017-01-03    19.000  81.888889    4.016667   1018.333333         hot
3    2017-01-04    19.000  70.050000    4.545000   1015.700000         hot
4    2017-01-05    19.000  74.944444    3.300000   1014.333333         hot
..          ...       ...        ...         ...           ...         ...
109  2017-04-20    34.500  27.500000    5.562500    998.625000        cold
110  2017-04-21    34.250  39.375000    6.962500    999.875000        cold
111  2017-04-22    32.900  40.900000    8.890000   1001.600000        cold
112  2017-04-23    32.875  27.500000    9.962500   1002.125000        cold
113  2017-04-24    32.000  27.142857   12.157143   1004.142857        cold

[114 rows x 6 columns]

In [106]:
#striping whitespaces from column names
data.columns = data.columns.str.strip()
data.columns

Index(['date', 'meantemp', 'humidity', 'wind_speed', 'meanpressure',
       'temperature'],
      dtype='object')

In [107]:
#rename columns
data = data.rename(columns ={'humidity':'avg_humidity'})
data

           date  meantemp  avg_humidity  wind_speed  meanpressure temperature
0    2017-01-01    19.000     85.869565    2.743478     59.000000         hot
1    2017-01-02    19.000     77.222222    2.894444   1018.277778         hot
2    2017-01-03    19.000     81.888889    4.016667   1018.333333         hot
3    2017-01-04    19.000     70.050000    4.545000   1015.700000         hot
4    2017-01-05    19.000     74.944444    3.300000   1014.333333         hot
..          ...       ...           ...         ...           ...         ...
109  2017-04-20    34.500     27.500000    5.562500    998.625000        cold
110  2017-04-21    34.250     39.375000    6.962500    999.875000        cold
111  2017-04-22    32.900     40.900000    8.890000   1001.600000        cold
112  2017-04-23    32.875     27.500000    9.962500   1002.125000        cold
113  2017-04-24    32.000     27.142857   12.157143   1004.142857        cold

[114 rows x 6 columns]

In [108]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          114 non-null    object
 1   meantemp      114 non-null    float64
 2   avg_humidity  114 non-null    float64
 3   wind_speed    114 non-null    float64
 4   meanpressure  114 non-null    float64
 5   temperature   114 non-null    object
dtypes: float64(4), object(2)
memory usage: 5.5+ KB

In [109]:
#type to integer
data['meanpressure.int'] = data['meanpressure'].astype('int')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              114 non-null    object
 1   meantemp          114 non-null    float64
 2   avg_humidity      114 non-null    float64
 3   wind_speed        114 non-null    float64
 4   meanpressure      114 non-null    float64
 5   temperature       114 non-null    object
 6   meanpressure.int  114 non-null    int32
dtypes: float64(4), int32(1), object(2)
memory usage: 5.9+ KB

In [110]:
#converting date column to datetime format
data['date'] = pd.to_datetime(data['date'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              114 non-null    datetime64[ns]
 1   meantemp          114 non-null    float64
 2   avg_humidity      114 non-null    float64
 3   wind_speed        114 non-null    float64
 4   meanpressure      114 non-null    float64
 5   temperature       114 non-null    object
 6   meanpressure.int  114 non-null    int32
dtypes: datetime64[ns](1), float64(4), int32(1), object(1)
memory usage: 5.9+ KB

In [111]:
#using the apply function
def categorize_temp(temp):
    if temp < 20:
        return 'cold'
    elif temp >= 20:
        return 'warm'
    else:
        return 'hot'

In [112]:
data['temperature_category'] = data['meantemp'].apply(categorize_temp)
data

,date,meantemp,avg_humidity,wind_speed,meanpressure,temperature,meanpressure.int,temperature_category
0,2017-01-01,19.000,85.869565,2.743478,59.000000,hot,59,cold
1,2017-01-02,19.000,77.222222,2.894444,1018.277778,hot,1018,cold
2,2017-01-03,19.000,81.888889,4.016667,1018.333333,hot,1018,cold
3,2017-01-04,19.000,70.050000,4.545000,1015.700000,hot,1015,cold
4,2017-01-05,19.000,74.944444,3.300000,1014.333333,hot,1014,cold
...,...,...,...,...,...,...,...,...
109,2017-04-20,34.500,27.500000,5.562500,998.625000,cold,998,warm
110,2017-04-21,34.250,39.375000,6.962500,999.875000,cold,999,warm
111,2017-04-22,32.900,40.900000,8.890000,1001.600000,cold,1001,warm
112,2017-04-23,32.875,27.500000,9.962500,1002.125000,cold,1002,warm
113,2017-04-24,32.000,27.142857,12.157143,1004.142857,cold,1004,warm

In [114]:
#.map function
data['month'] = data['date'].dt.month
data

,date,meantemp,avg_humidity,wind_speed,meanpressure,temperature,meanpressure.int,temperature_category,month
0,2017-01-01,19.000,85.869565,2.743478,59.000000,hot,59,cold,1
1,2017-01-02,19.000,77.222222,2.894444,1018.277778,hot,1018,cold,1
2,2017-01-03,19.000,81.888889,4.016667,1018.333333,hot,1018,cold,1
3,2017-01-04,19.000,70.050000,4.545000,1015.700000,hot,1015,cold,1
4,2017-01-05,19.000,74.944444,3.300000,1014.333333,hot,1014,cold,1
...,...,...,...,...,...,...,...,...,...
109,2017-04-20,34.500,27.500000,5.562500,998.625000,cold,998,warm,4
110,2017-04-21,34.250,39.375000,6.962500,999.875000,cold,999,warm,4
111,2017-04-22,32.900,40.900000,8.890000,1001.600000,cold,1001,warm,4
112,2017-04-23,32.875,27.500000,9.962500,1002.125000,cold,1002,warm,4
113,2017-04-24,32.000,27.142857,12.157143,1004.142857,cold,1004,warm,4

In [ ]:
month_map = {1:'Jan',2:'Feb',3:'March',4:'April',5:'May',6:'Jun',7:'Jul',8:'Aug',9:'Sep'}
data['month_name']